### PR TITLE
Convert any nickname on the message.

### PR DESCRIPTION
**Pull request by lunks**
I often use nicknames on the message and ping several people. This makes sure I don't expose IRC nicknames and show proper Campfire usernames.

### CODE REVIEW

**Comment by zerowidth** [comment]
I like the idea, but there's two things I'd think about:
1. Change the regex to match on word boundaries, that way "nathan" wouldn't also match "jonathan" by accident
2. make it configurable, as I think this could lead to surprising output in some cases, and being on the translated side of things, you may not even notice.

**Comment by lunks** [comment]
1. :+1: 
2. What kind of surprises? I've been hit by not having this implemented, i.e. I mentioned someone and thought it was being translated. We could have something to toggle nick translation, but IMHO this specific PR is for addressing expectations I have when mentioning someone in the middle of a message.

**Comment by zerowidth** [comment]
Re: surprises, I'm just sensitive to the fact that because camper van is a translation layer, you never really _see_ what other people see. So if nicks were to be incorrectly converted (e.g. mid-word, which you've fixed) you'd never notice it. That's why I limited the replacement to `^nick:` so it'd be predictable.

I suppose as long as no one's got a nickname that matches a common term that you're discussing in chat, it'd be just fine!

**Comment by lunks** [comment]
If it matches a common term, there's not much to be done. The user would probably be highlighted anyway. I, at least, can't think of a common term that could be messed when translating, i.e. if it's a single word the only difference would be the first letter being capitalized and as such not really an issue.

I see your concern, but I can't figure out any example. Perhaps you know one and are not telling me? :trollface:

**Comment by zerowidth** [comment]
Nah, I didn't have any specific examples, just paranoia. This looks fine, go for it.

**Comment by lunks** [comment]
Alright, thanks for the input!

**Pull request merged**
