### PR TITLE
Change required ruby version to > 1.9.2

### PR DESCRIPTION
**Pull request by haileys**
Tests pass on 1.9.2, 1.9.3 and 2.0.0.

### CODE REVIEW

**Comment by calebhearth** [comment]
Can you release a new version so that this can be run without needing to install an older ruby version?

**Comment by rh0** [comment]
You could force the installation with `gem install -f camper_van`

**Comment by calebhearth** [comment]
Sure, I got it installed from the source.

I still think it is a good idea to release a new version so that installing your gem isn't something that needs a workaround.

**Comment by epugh** [comment]
I agree.  From what I've seen of camper_van, and the various patches and conversation around it, it's meant for folks who are hard core Ruby developers, who grok all the nuances of gems, ruby versions, bundler, and the rest.  For those of us who just want to have Campfire show up in IRC, not so sure....  ;-)

On Jun 28, 2013, at 7:12 PM, Caleb Thompson wrote:

> Sure, I got it installed from the source.
> 
> I still think it is a good idea to release a new version so that installing your gem isn't something that needs a workaround.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Eric Pugh | Principal | OpenSource Connections, LLC | 434.466.1467 | http://www.opensourceconnections.com
Co-Author: Apache Solr 3 Enterprise Search Server available from http://www.packtpub.com/apache-solr-3-enterprise-search-server/book  
This e-mail and all contents, including attachments, is considered to be Company Confidential unless explicitly stated otherwise, regardless of whether attachments are marked as such.

**Comment by zerowidth** [comment]
Released a new version, thanks!

**Pull request merged**
